config/routes.rb
Rails.application.routes.draw do
  match ':controller(/:action(/:id))',:via => [:get, :post]
  get "people/index"
  root 'people#index'

end

app/models/person.rb
class Person < ActiveRecord::Base

	validates_presence_of :name
	validates_length_of :name, :maximum => 35, :message => "Please write a short name."
	validates_presence_of :phone
	validates_length_of :phone, :is => 10, :message => "Please enter a 10 digit number(include STD code)."
	validates_presence_of :location
	validates_presence_of :status

	searchable do
		text :name, :boost => 3 
		text :phone, :location, :status		
	end

	if :ipaddress
		geocoded_by :ipaddress,
  			:latitude => :latitude, :longitude => :longitude
		after_validation :geocode
	else
		geocoded_by :location,
  			:latitude => :latitude, :longitude => :longitude
		after_validation :geocode
	end	

	before_save :concatenate_chennai

  	def concatenate_chennai
     	self.location = "#{location},Tamil Nadu,India"
  	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController



	def index
		#@people = Person.order("name ASC").group("location")
		@search = Person.search do
			fulltext params[:search]
		end
		#@people = Person.search params[:search]
		@people = @search.results
	end

	def new
		@person = Person.new
	end

	def create
		@person = Person.new(params.require(:person).permit(:name, :location, :phone, :status, :ipaddress))
		#@person.ipaddress = request.env['REMOTE_ADDR'].to_s
		@person.ipaddress = '182.68.7.34'
		if @person.save
			redirect_to(:action => 'index')
			flash[:notice] = "Person successfully added."
		else
			render('new')
		end
	end

	def delete
		@person = Person.find(params[:id])
	end

	def destroy
		person = Person.find(params[:id])
		person.destroy
		redirect_to(:action => 'index')
		flash[:notice] = "Deleted successfully"
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Msafe</title>
  <!--script src="http://maps.google.com/maps/api/js?sensor=false" type="text/javascript">
  </script-->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
   <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCBFavoQ-TL4TuoxVemjogjoRLQCVtFW-w"></script>
   <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<body>
<div id="wrapper">
<%= yield %>
</div>

</body>


</html>

app/views/people/delete.html.erb
<% if !flash[:notice].blank? %>
  <div class="notice">
    <%= flash[:notice] %>
  </div>
<% end %>

<%= link_to("<< Back to List", {:action => 'index'}, :class => 'back-link') %>

<div class="Delete">
  <h2>Delete Person</h2>

  <%= form_for(:person, :url => {:action => 'destroy', :id => @person.id}) do |f| %>

    <p>Are you sure you want to permanently delete this person?</p>

    <p class="reference-name"><%= @person.name %></p>

    <div class="form-buttons">
      <%= submit_tag("Delete") %>
    </div>

  <% end %>
</div>

app/views/people/index.html.erb
<% if !flash[:notice].blank? %>
  <div class="notice">
    <%= flash[:notice] %>
  </div>
<% end %>



<div class="people index">
  <h1>Msafe : Mark yourself safe</h1>
    
  <br>

  <div id="map" style="width: 100%; height: 400px;"></div>

  <br><br><br>
  <%= link_to("Add New Person", {:action => 'new'}, :class => 'action new btn',  :onclick => 'getLocation();') %>

  <br><br><br>
  
  <%= form_tag people_index_path, :method => :get do %>
  <p>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Search", :name => nil %>
  </p>
<% end %>
  <table class="listing" summary="Person list">
    <tr class="header">
      <th>Name</th>
      <th>Phone</th>
      <th>Location</th>
      <th>Status</th>
    </tr>
    <% @people.each do |person| %>
    <tr>
      <!-- <td><%= person.id %></td> -->
      <td><%= person.name %></td>
      <td class="center"><%= person.phone %></td>
      <td class="center"><%= person.location %></td>
      <td class="center"><%= person.status.upcase %></td>
      <td class="center"><%= person.ipaddress %></td>
      <td class="action">
        <%= link_to("Delete", {:action => 'delete', :id => person.id}, :class => 'action delete') %>
      </td>
    </tr>
    <% end %>
  </table>
</div>

<br><br><br>

 <script>

   var locations = [<% @people.each do |person| %>
            ['<%= person.location %>',<%= person.latitude %>,<%= person.longitude %>],
           <% end %>  
          ];
    

    var map = new google.maps.Map(document.getElementById('map'), {
      zoom: 8,
      center: new google.maps.LatLng(13.082680, 80.270718),
      mapTypeId: google.maps.MapTypeId.ROADMAP
    });

    var infowindow = new google.maps.InfoWindow();

    var infoWindowContent = [ <% @people.each do |person| %>
        ['<div class="info_content">' + '<h3>Name: <%= person.name %><br>Located at: <%= person.location %><br>Status: <%= person.status.upcase %><br><%= person.phone %></h3>'+'</div>'],
        <% end %>  
    ];

    var marker, i;

    for (i = 0; i < locations.length; i++) {  
      marker = new google.maps.Marker({
        position: new google.maps.LatLng(locations[i][1], locations[i][2]),
        map: map
      });

      google.maps.event.addListener(marker, 'click', (function(marker, i) {
        return function() {
          infowindow.setContent(infoWindowContent[i][0]);
          infowindow.open(map, marker);
        }
      })(marker, i));

    }

    //------------------

    
 </script>
  

    

app/views/people/new.html.erb
<% if !flash[:notice].blank? %>
  <div class="notice">
    <%= flash[:notice] %>
  </div>
<% end %>
<br><br>
<%= link_to("<< Back to List", {:action => 'index'}, :class => 'back-link') %>

<div class="people new">
  <h2>Add Person</h2>

  <%= form_for(:person, :url => {:action => 'create'}) do |f| %>

    <table summary="Person form fields">
      <tr>
        <th>Name</th>
        <td><%= f.text_field(:name) %></td>
      </tr>
      <tr>
        <th>Phone</th>
        <td><%= f.text_field(:phone) %></td>
      </tr>
      
      <tr>
        <th>Location</th>
        <td><%= f.text_field(:location) %></td>
      </tr>

      <tr>
        <th>Status (Safe,Stranded etc.)</th>
        <td><%= f.text_field(:status) %></td>
      </tr>
    </table>

    <div class="form-buttons" id="add_btn">
      <%= submit_tag("Add Person") %>
    </div>

  <% end %>
</div>

<script>
  

function getLocation() {
      if (navigator.geolocation) {
          navigator.geolocation.getCurrentPosition(savePosition, positionError, {timeout:10000});
      } else {
          alert ("Geolocation is not supported by this browser");
      }
  }

  // handle the error here
  function positionError(error) {
      var errorCode = error.code;
      var message = error.message;

      alert(message);
  }

  function savePosition(position) {
            
  }

$(document).ready(function(){
    $("#add_btn").click(function(){
        getLocation();
    });
});

</script